function [M,h] = func_Mh(in1)
%FUNC_MH
%    [M,H] = FUNC_MH(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    05-Sep-2020 09:24:59

q = in1(4,:);
q_D = in1(8,:);
theta_D = in1(7,:);
theta = in1(3,:);
M = reshape([5.0,0.0,cos(q+theta).*(-3.0./1.0e+1)-cos(theta).*(3.0./1.0e+1),cos(q+theta).*(-3.0./1.0e+1),0.0,5.0,sin(q+theta).*(3.0./1.0e+1)+sin(theta).*(3.0./1.0e+1),sin(q+theta).*(3.0./1.0e+1),cos(q+theta).*(-3.0./1.0e+1)-cos(theta).*(3.0./1.0e+1),sin(q+theta).*(3.0./1.0e+1)+sin(theta).*(3.0./1.0e+1),cos(q).*(3.0./5.0e+1)+7.0./5.0e+1,cos(q).*(3.0./1.0e+2)+1.0./1.0e+1,cos(q+theta).*(-3.0./1.0e+1),sin(q+theta).*(3.0./1.0e+1),cos(q).*(3.0./1.0e+2)+1.0./1.0e+1,1.0./1.0e+1],[4,4]);
if nargout > 1
    h = [theta_D.^2.*sin(theta).*(3.0./1.0e+1)+q_D.^2.*sin(q+theta).*(3.0./1.0e+1)+theta_D.^2.*sin(q+theta).*(3.0./1.0e+1)+q_D.*theta_D.*sin(q+theta).*(3.0./5.0);theta_D.^2.*cos(theta).*(3.0./1.0e+1)+q_D.^2.*cos(q+theta).*(3.0./1.0e+1)+theta_D.^2.*cos(q+theta).*(3.0./1.0e+1)+q_D.*theta_D.*cos(q+theta).*(3.0./5.0)+4.9e+1;sin(q+theta).*(1.47e+2./5.0e+1)+sin(theta).*(1.47e+2./5.0e+1)-q_D.^2.*sin(q).*(3.0./1.0e+2)-q_D.*theta_D.*sin(q).*(3.0./5.0e+1);sin(q+theta).*(1.47e+2./5.0e+1)+theta_D.^2.*sin(q).*(3.0./1.0e+2)];
end
