function ut = func_thrusters(in1,in2,in3)
%FUNC_THRUSTERS
%    UT = FUNC_THRUSTERS(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-Jul-2020 06:26:29

Lt_L_1 = in2(32,:);
Lt_L_2 = in2(33,:);
Lt_L_3 = in2(34,:);
Lt_R_1 = in2(35,:);
Lt_R_2 = in2(36,:);
Lt_R_3 = in2(37,:);
Rb_1_1 = in1(18,:);
Rb_1_2 = in1(21,:);
Rb_1_3 = in1(24,:);
Rb_2_1 = in1(19,:);
Rb_2_2 = in1(22,:);
Rb_2_3 = in1(25,:);
Rb_3_1 = in1(20,:);
Rb_3_2 = in1(23,:);
Rb_3_3 = in1(26,:);
ftL_1 = in3(1,:);
ftL_2 = in3(2,:);
ftL_3 = in3(3,:);
ftR_1 = in3(4,:);
ftR_2 = in3(5,:);
ftR_3 = in3(6,:);
ut = [0.0;0.0;0.0;0.0;ftL_1+ftR_1;ftL_2+ftR_2;ftL_3+ftR_3;ftL_1.*(Lt_L_2.*Rb_1_3-Lt_L_3.*Rb_1_2)+ftL_2.*(Lt_L_2.*Rb_2_3-Lt_L_3.*Rb_2_2)+ftL_3.*(Lt_L_2.*Rb_3_3-Lt_L_3.*Rb_3_2)+ftR_1.*(Lt_R_2.*Rb_1_3-Lt_R_3.*Rb_1_2)+ftR_2.*(Lt_R_2.*Rb_2_3-Lt_R_3.*Rb_2_2)+ftR_3.*(Lt_R_2.*Rb_3_3-Lt_R_3.*Rb_3_2);-ftL_1.*(Lt_L_1.*Rb_1_3-Lt_L_3.*Rb_1_1)-ftL_2.*(Lt_L_1.*Rb_2_3-Lt_L_3.*Rb_2_1)-ftL_3.*(Lt_L_1.*Rb_3_3-Lt_L_3.*Rb_3_1)-ftR_1.*(Lt_R_1.*Rb_1_3-Lt_R_3.*Rb_1_1)-ftR_2.*(Lt_R_1.*Rb_2_3-Lt_R_3.*Rb_2_1)-ftR_3.*(Lt_R_1.*Rb_3_3-Lt_R_3.*Rb_3_1);ftL_1.*(Lt_L_1.*Rb_1_2-Lt_L_2.*Rb_1_1)+ftL_2.*(Lt_L_1.*Rb_2_2-Lt_L_2.*Rb_2_1)+ftL_3.*(Lt_L_1.*Rb_3_2-Lt_L_2.*Rb_3_1)+ftR_1.*(Lt_R_1.*Rb_1_2-Lt_R_2.*Rb_1_1)+ftR_2.*(Lt_R_1.*Rb_2_2-Lt_R_2.*Rb_2_1)+ftR_3.*(Lt_R_1.*Rb_3_2-Lt_R_2.*Rb_3_1)];
