function accel = func_dynamics_c(in1,in2,in3,in4)
%FUNC_DYNAMICS_C
%    ACCEL = FUNC_DYNAMICS_C(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Aug-2020 17:19:58

ft_1 = in2(1,:);
ft_2 = in2(2,:);
ft_3 = in2(3,:);
g = in4(2,:);
m = in4(1,:);
u_1 = in3(1,:);
u_2 = in3(2,:);
u_3 = in3(3,:);
vr = in2(4,:);
xc_1 = in1(1,:);
xc_2 = in1(2,:);
xc_3 = in1(3,:);
accel = [(ft_1-((u_1-xc_1).*(((ft_1-vr).*(u_1-xc_1))./m+((ft_2-vr).*(u_2-xc_2))./m-((u_3-xc_3).*(-ft_3+vr+g.*m))./m))./((u_1-xc_1).^2./m+(u_2-xc_2).^2./m+(u_3-xc_3).^2./m))./m;(ft_2-((u_2-xc_2).*(((ft_1-vr).*(u_1-xc_1))./m+((ft_2-vr).*(u_2-xc_2))./m-((u_3-xc_3).*(-ft_3+vr+g.*m))./m))./((u_1-xc_1).^2./m+(u_2-xc_2).^2./m+(u_3-xc_3).^2./m))./m;-(-ft_3+g.*m+((u_3-xc_3).*(((ft_1-vr).*(u_1-xc_1))./m+((ft_2-vr).*(u_2-xc_2))./m-((u_3-xc_3).*(-ft_3+vr+g.*m))./m))./((u_1-xc_1).^2./m+(u_2-xc_2).^2./m+(u_3-xc_3).^2./m))./m];
