function [pos_foot_L,pos_foot_R] = func_foot_pos(in1,in2)
%FUNC_FOOT_POS
%    [POS_FOOT_L,POS_FOOT_R] = FUNC_FOOT_POS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-Jul-2020 06:26:29

L1_L_1 = in2(11,:);
L1_L_2 = in2(12,:);
L1_L_3 = in2(13,:);
L1_R_1 = in2(20,:);
L1_R_2 = in2(21,:);
L1_R_3 = in2(22,:);
L2_L_1 = in2(14,:);
L2_L_2 = in2(15,:);
L2_L_3 = in2(16,:);
L2_R_1 = in2(23,:);
L2_R_2 = in2(24,:);
L2_R_3 = in2(25,:);
L3_L_1 = in2(17,:);
L3_L_2 = in2(18,:);
L3_L_3 = in2(19,:);
L3_R_1 = in2(26,:);
L3_R_2 = in2(27,:);
L3_R_3 = in2(28,:);
Rb_1_1 = in1(18,:);
Rb_1_2 = in1(21,:);
Rb_1_3 = in1(24,:);
Rb_2_1 = in1(19,:);
Rb_2_2 = in1(22,:);
Rb_2_3 = in1(25,:);
Rb_3_1 = in1(20,:);
Rb_3_2 = in1(23,:);
Rb_3_3 = in1(26,:);
l4a = in2(29,:);
l4b = in2(30,:);
q_hF_1 = in1(1,:);
q_hF_2 = in1(3,:);
q_hS_1 = in1(2,:);
q_hS_2 = in1(4,:);
q_kS_1 = in1(27,:);
q_kS_2 = in1(28,:);
xb_1 = in1(5,:);
xb_2 = in1(6,:);
xb_3 = in1(7,:);
pos_foot_L = [xb_1+L2_L_2.*(Rb_1_2.*cos(q_hF_1)+Rb_1_3.*sin(q_hF_1))+L2_L_3.*(Rb_1_3.*cos(q_hF_1)-Rb_1_2.*sin(q_hF_1))+L3_L_2.*(Rb_1_2.*cos(q_hF_1)+Rb_1_3.*sin(q_hF_1))+L3_L_1.*(Rb_1_1.*cos(q_hS_1)-sin(q_hS_1).*(Rb_1_3.*cos(q_hF_1)-Rb_1_2.*sin(q_hF_1)))+L3_L_3.*(Rb_1_1.*sin(q_hS_1)+cos(q_hS_1).*(Rb_1_3.*cos(q_hF_1)-Rb_1_2.*sin(q_hF_1)))-(l4b+l4a.*sin(q_kS_1)).*(Rb_1_1.*sin(q_hS_1)+cos(q_hS_1).*(Rb_1_3.*cos(q_hF_1)-Rb_1_2.*sin(q_hF_1)))+L1_L_1.*Rb_1_1+L1_L_2.*Rb_1_2+L1_L_3.*Rb_1_3+L2_L_1.*Rb_1_1-l4a.*cos(q_kS_1).*(Rb_1_1.*cos(q_hS_1)-sin(q_hS_1).*(Rb_1_3.*cos(q_hF_1)-Rb_1_2.*sin(q_hF_1)));xb_2+L2_L_2.*(Rb_2_2.*cos(q_hF_1)+Rb_2_3.*sin(q_hF_1))+L2_L_3.*(Rb_2_3.*cos(q_hF_1)-Rb_2_2.*sin(q_hF_1))+L3_L_2.*(Rb_2_2.*cos(q_hF_1)+Rb_2_3.*sin(q_hF_1))+L3_L_1.*(Rb_2_1.*cos(q_hS_1)-sin(q_hS_1).*(Rb_2_3.*cos(q_hF_1)-Rb_2_2.*sin(q_hF_1)))+L3_L_3.*(Rb_2_1.*sin(q_hS_1)+cos(q_hS_1).*(Rb_2_3.*cos(q_hF_1)-Rb_2_2.*sin(q_hF_1)))-(l4b+l4a.*sin(q_kS_1)).*(Rb_2_1.*sin(q_hS_1)+cos(q_hS_1).*(Rb_2_3.*cos(q_hF_1)-Rb_2_2.*sin(q_hF_1)))+L1_L_1.*Rb_2_1+L1_L_2.*Rb_2_2+L1_L_3.*Rb_2_3+L2_L_1.*Rb_2_1-l4a.*cos(q_kS_1).*(Rb_2_1.*cos(q_hS_1)-sin(q_hS_1).*(Rb_2_3.*cos(q_hF_1)-Rb_2_2.*sin(q_hF_1)));xb_3+L2_L_2.*(Rb_3_2.*cos(q_hF_1)+Rb_3_3.*sin(q_hF_1))+L2_L_3.*(Rb_3_3.*cos(q_hF_1)-Rb_3_2.*sin(q_hF_1))+L3_L_2.*(Rb_3_2.*cos(q_hF_1)+Rb_3_3.*sin(q_hF_1))+L3_L_1.*(Rb_3_1.*cos(q_hS_1)-sin(q_hS_1).*(Rb_3_3.*cos(q_hF_1)-Rb_3_2.*sin(q_hF_1)))+L3_L_3.*(Rb_3_1.*sin(q_hS_1)+cos(q_hS_1).*(Rb_3_3.*cos(q_hF_1)-Rb_3_2.*sin(q_hF_1)))-(l4b+l4a.*sin(q_kS_1)).*(Rb_3_1.*sin(q_hS_1)+cos(q_hS_1).*(Rb_3_3.*cos(q_hF_1)-Rb_3_2.*sin(q_hF_1)))+L1_L_1.*Rb_3_1+L1_L_2.*Rb_3_2+L1_L_3.*Rb_3_3+L2_L_1.*Rb_3_1-l4a.*cos(q_kS_1).*(Rb_3_1.*cos(q_hS_1)-sin(q_hS_1).*(Rb_3_3.*cos(q_hF_1)-Rb_3_2.*sin(q_hF_1)))];
if nargout > 1
    pos_foot_R = [xb_1+L2_R_2.*(Rb_1_2.*cos(q_hF_2)+Rb_1_3.*sin(q_hF_2))+L2_R_3.*(Rb_1_3.*cos(q_hF_2)-Rb_1_2.*sin(q_hF_2))+L3_R_2.*(Rb_1_2.*cos(q_hF_2)+Rb_1_3.*sin(q_hF_2))+L3_R_1.*(Rb_1_1.*cos(q_hS_2)-sin(q_hS_2).*(Rb_1_3.*cos(q_hF_2)-Rb_1_2.*sin(q_hF_2)))+L3_R_3.*(Rb_1_1.*sin(q_hS_2)+cos(q_hS_2).*(Rb_1_3.*cos(q_hF_2)-Rb_1_2.*sin(q_hF_2)))-(l4b+l4a.*sin(q_kS_2)).*(Rb_1_1.*sin(q_hS_2)+cos(q_hS_2).*(Rb_1_3.*cos(q_hF_2)-Rb_1_2.*sin(q_hF_2)))+L1_R_1.*Rb_1_1+L1_R_2.*Rb_1_2+L1_R_3.*Rb_1_3+L2_R_1.*Rb_1_1-l4a.*cos(q_kS_2).*(Rb_1_1.*cos(q_hS_2)-sin(q_hS_2).*(Rb_1_3.*cos(q_hF_2)-Rb_1_2.*sin(q_hF_2)));xb_2+L2_R_2.*(Rb_2_2.*cos(q_hF_2)+Rb_2_3.*sin(q_hF_2))+L2_R_3.*(Rb_2_3.*cos(q_hF_2)-Rb_2_2.*sin(q_hF_2))+L3_R_2.*(Rb_2_2.*cos(q_hF_2)+Rb_2_3.*sin(q_hF_2))+L3_R_1.*(Rb_2_1.*cos(q_hS_2)-sin(q_hS_2).*(Rb_2_3.*cos(q_hF_2)-Rb_2_2.*sin(q_hF_2)))+L3_R_3.*(Rb_2_1.*sin(q_hS_2)+cos(q_hS_2).*(Rb_2_3.*cos(q_hF_2)-Rb_2_2.*sin(q_hF_2)))-(l4b+l4a.*sin(q_kS_2)).*(Rb_2_1.*sin(q_hS_2)+cos(q_hS_2).*(Rb_2_3.*cos(q_hF_2)-Rb_2_2.*sin(q_hF_2)))+L1_R_1.*Rb_2_1+L1_R_2.*Rb_2_2+L1_R_3.*Rb_2_3+L2_R_1.*Rb_2_1-l4a.*cos(q_kS_2).*(Rb_2_1.*cos(q_hS_2)-sin(q_hS_2).*(Rb_2_3.*cos(q_hF_2)-Rb_2_2.*sin(q_hF_2)));xb_3+L2_R_2.*(Rb_3_2.*cos(q_hF_2)+Rb_3_3.*sin(q_hF_2))+L2_R_3.*(Rb_3_3.*cos(q_hF_2)-Rb_3_2.*sin(q_hF_2))+L3_R_2.*(Rb_3_2.*cos(q_hF_2)+Rb_3_3.*sin(q_hF_2))+L3_R_1.*(Rb_3_1.*cos(q_hS_2)-sin(q_hS_2).*(Rb_3_3.*cos(q_hF_2)-Rb_3_2.*sin(q_hF_2)))+L3_R_3.*(Rb_3_1.*sin(q_hS_2)+cos(q_hS_2).*(Rb_3_3.*cos(q_hF_2)-Rb_3_2.*sin(q_hF_2)))-(l4b+l4a.*sin(q_kS_2)).*(Rb_3_1.*sin(q_hS_2)+cos(q_hS_2).*(Rb_3_3.*cos(q_hF_2)-Rb_3_2.*sin(q_hF_2)))+L1_R_1.*Rb_3_1+L1_R_2.*Rb_3_2+L1_R_3.*Rb_3_3+L2_R_1.*Rb_3_1-l4a.*cos(q_kS_2).*(Rb_3_1.*cos(q_hS_2)-sin(q_hS_2).*(Rb_3_3.*cos(q_hF_2)-Rb_3_2.*sin(q_hF_2)))];
end
